### ISSUE TITLE
Local (multiprocessing) mode has intermittent IOBlocking Error on prints

### ISSUE THREAD

**Issue by shuds13** [Libensemble/libensemble#167]
E.g.

---- Received error message from 2 ----
Message: [Errno 11] write could not complete without blocking
Traceback (most recent call last):
  File "/home/jlarson/research/libensemble/libensemble/libE_worker.py", line 264, in run
    response = self._handle(Work)
  File "/home/jlarson/research/libensemble/libensemble/libE_worker.py", line 235, in _handle
    calc_out, persis_info, calc_status = self._handle_calc(Work, calc_in)
  File "/home/jlarson/research/libensemble/libensemble/libE_worker.py", line 176, in _handle_calc
    out = calc(calc_in, Work['persis_info'], Work['libE_info'])
  File "/home/jlarson/research/libensemble/libensemble/libE_worker.py", line 120, in run_sim
    return sim_f(calc_in, persis_info, sim_specs, libE_info)
  File "/home/jlarson/research/libensemble/libensemble/sim_funcs/job_control_hworld.py", line 91, in job_control_hworld
    job, calc_status = polling_loop(comm, jobctl, job, timeout)
  File "/home/jlarson/research/libensemble/libensemble/sim_funcs/job_control_hworld.py", line 33, in polling_loop
    print('Job {} still running on worker {} ....'.format(job.id, jobctl.workerID))
BlockingIOError: [Errno 11] write could not complete without blocking

--------

Manager exception raised .. aborting ensemble:

See PR #165 for more details.

Only seems to occur occasionaly on some platforms and hard to reproduce.

Action:
Try and to make a reproducer.

Possible soln:
import fcntl; fcntl.fcntl(1, fcntl.F_SETFL, 0)
from travis-ci/travis-ci#8920

**Comment by jlnav** [comment]
Closing, since we haven't seen this issue in a while
