### ISSUE TITLE
Creating/copying sim_dirs makes unexpected errors

### ISSUE THREAD

**Issue by jmlarson1** [Libensemble/libensemble#520]
When running on Bebop (on the `bugfix/sim_dir_errors/` branch) I get the following errors. 

Perhaps the run is set up incorrectly, but it should (hopefully) give a better idea of what is the issue. 

Any idea as to why there are so many "FileExistErrors" during the run?

```
[jmlarson@beboplogin3 regression_tests]$ \rm -rf my_ensemble/ /scratch/my_ensemble/

[jmlarson@beboplogin3 regression_tests]$ mpiexec -np 4 python3 test_beam_loading.py 
[0] libensemble.libE (ERROR): ---- Received error message from 1 ----
[0] libensemble.libE (ERROR): Message: [Errno 17] File exists: '/scratch/my_ensemble/worker1/sim0/'
[0] libensemble.libE (ERROR): Traceback (most recent call last):
  File "/gpfs/fs1/home/jmlarson/research/libensemble/libensemble/libE_worker.py", line 465, in run
    response = self._handle(Work)
  File "/gpfs/fs1/home/jmlarson/research/libensemble/libensemble/libE_worker.py", line 435, in _handle
    calc_out, persis_info, calc_status = self._handle_calc(Work, calc_in)
  File "/gpfs/fs1/home/jmlarson/research/libensemble/libensemble/libE_worker.py", line 363, in _handle_calc
    out = self._determine_dir_then_calc(Work, calc_type, calc_in, calc)
  File "/gpfs/fs1/home/jmlarson/research/libensemble/libensemble/libE_worker.py", line 318, in _determine_dir_then_calc
    H_rows, calc_str, self.loc_stack)
  File "/gpfs/fs1/home/jmlarson/research/libensemble/libensemble/libE_worker.py", line 208, in _make_calc_dir
    symlink_files=symlink_files)
  File "/gpfs/fs1/home/jmlarson/research/libensemble/libensemble/utils/loc_stack.py", line 78, in register_loc
    self.copy_or_symlink(dirname, copy_files, symlink_files, ignore_FileExists)
  File "/gpfs/fs1/home/jmlarson/research/libensemble/libensemble/utils/loc_stack.py", line 27, in copy_or_symlink
    shutil.copytree(file_path, dest_path)
  File "/soft/anaconda3/5.2.0/lib/python3.6/shutil.py", line 315, in copytree
    os.makedirs(dst)
  File "/soft/anaconda3/5.2.0/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/scratch/my_ensemble/worker1/sim0/'

[0] libensemble.libE (ERROR): Manager exception raised .. aborting ensemble:
[0] libensemble.libE (ERROR): Dumping ensemble history with 0 sims evaluated:
Traceback (most recent call last):
  File "test_beam_loading.py", line 35, in <module>
    persis_info, libE_specs=libE_specs)
  File "/gpfs/fs1/home/jmlarson/research/libensemble/libensemble/libE.py", line 139, in libE
    persis_info, alloc_specs, libE_specs, H0)
  File "/gpfs/fs1/home/jmlarson/research/libensemble/libensemble/libE.py", line 238, in libE_mpi
    libE_mpi_worker(comm, sim_specs, gen_specs, libE_specs)
  File "/gpfs/fs1/home/jmlarson/research/libensemble/libensemble/libE.py", line 273, in libE_mpi_worker
    worker_main(comm, sim_specs, gen_specs, libE_specs, log_comm=True)
  File "/gpfs/fs1/home/jmlarson/research/libensemble/libensemble/libE_worker.py", line 81, in worker_main
    worker.run()
  File "/gpfs/fs1/home/jmlarson/research/libensemble/libensemble/libE_worker.py", line 476, in run
    self._copy_back()
  File "/gpfs/fs1/home/jmlarson/research/libensemble/libensemble/libE_worker.py", line 284, in _copy_back
    shutil.copytree(dir, dest_path, symlinks=True)
  File "/soft/anaconda3/5.2.0/lib/python3.6/shutil.py", line 315, in copytree
    os.makedirs(dst)
  File "/soft/anaconda3/5.2.0/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: 'my_ensemble/worker1'
Traceback (most recent call last):
  File "test_beam_loading.py", line 35, in <module>
    persis_info, libE_specs=libE_specs)
  File "/gpfs/fs1/home/jmlarson/research/libensemble/libensemble/libE.py", line 139, in libE
    persis_info, alloc_specs, libE_specs, H0)
  File "/gpfs/fs1/home/jmlarson/research/libensemble/libensemble/libE.py", line 238, in libE_mpi
    libE_mpi_worker(comm, sim_specs, gen_specs, libE_specs)
  File "/gpfs/fs1/home/jmlarson/research/libensemble/libensemble/libE.py", line 273, in libE_mpi_worker
    worker_main(comm, sim_specs, gen_specs, libE_specs, log_comm=True)
  File "/gpfs/fs1/home/jmlarson/research/libensemble/libensemble/libE_worker.py", line 81, in worker_main
    worker.run()
  File "/gpfs/fs1/home/jmlarson/research/libensemble/libensemble/libE_worker.py", line 476, in run
    self._copy_back()
  File "/gpfs/fs1/home/jmlarson/research/libensemble/libensemble/libE_worker.py", line 284, in _copy_back
    shutil.copytree(dir, dest_path, symlinks=True)
  File "/soft/anaconda3/5.2.0/lib/python3.6/shutil.py", line 315, in copytree
    os.makedirs(dst)
  File "/soft/anaconda3/5.2.0/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: 'my_ensemble/worker3'
Traceback (most recent call last):
  File "test_beam_loading.py", line 35, in <module>
    persis_info, libE_specs=libE_specs)
  File "/gpfs/fs1/home/jmlarson/research/libensemble/libensemble/libE.py", line 139, in libE
    persis_info, alloc_specs, libE_specs, H0)
  File "/gpfs/fs1/home/jmlarson/research/libensemble/libensemble/libE.py", line 238, in libE_mpi
    libE_mpi_worker(comm, sim_specs, gen_specs, libE_specs)
  File "/gpfs/fs1/home/jmlarson/research/libensemble/libensemble/libE.py", line 273, in libE_mpi_worker
    worker_main(comm, sim_specs, gen_specs, libE_specs, log_comm=True)
  File "/gpfs/fs1/home/jmlarson/research/libensemble/libensemble/libE_worker.py", line 81, in worker_main
    worker.run()
  File "/gpfs/fs1/home/jmlarson/research/libensemble/libensemble/libE_worker.py", line 476, in run
    self._copy_back()
  File "/gpfs/fs1/home/jmlarson/research/libensemble/libensemble/libE_worker.py", line 284, in _copy_back
    shutil.copytree(dir, dest_path, symlinks=True)
  File "/soft/anaconda3/5.2.0/lib/python3.6/shutil.py", line 315, in copytree
    os.makedirs(dst)
  File "/soft/anaconda3/5.2.0/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: 'my_ensemble/worker2'
application called MPI_Abort(comm=0x84000004, 1) - process 0

```

**Comment by jmlarson1** [comment]
Note that the regression test passes without error:

```
[jmlarson@beboplogin3 regression_tests]$ mpiexec -np 4 python3 test_sim_dirs_per_worker.py 
creating ensemble dir:  ../ensemble_workdirs_w3_mpi
creating ensemble dir:  ../ensemble_workdirs_w3_mpi
creating ensemble dir:  ../ensemble_workdirs_w3_mpi
creating ensemble dir:  ../ensemble_workdirs_w3_mpi
```

**Comment by jlnav** [comment]
- [ ] Update check_inputs to check and account for confusing mandatory datatypes for sim_dir options

**Comment by jmlarson1** [comment]
And probably gen_dir too.

**Comment by jlnav** [comment]
Closeds by #523
