### ISSUE TITLE
Default alloc_f fails with KeyError when using empty persis_info

### ISSUE THREAD

**Issue by jlnav** [Libensemble/libensemble#571]
``persis_info = {}``

```
[0] libensemble.libE (ERROR): Traceback (most recent call last):
  File "/Users/John-Luke/Desktop/libensemble/libensemble/libensemble/libE.py", line 155, in libE_manager
    exit_criteria, persis_info, wcomms)
  File "/Users/John-Luke/Desktop/libensemble/libensemble/libensemble/libE_manager.py", line 88, in manager_main
    result = mgr.run(persis_info)
  File "/Users/John-Luke/Desktop/libensemble/libensemble/libensemble/libE_manager.py", line 475, in run
    persis_info)
  File "/Users/John-Luke/Desktop/libensemble/libensemble/libensemble/libE_manager.py", line 449, in _alloc_work
    output = alloc_f(self.W, H, self.sim_specs, self.gen_specs, self.alloc_specs, persis_info)
  File "/Users/John-Luke/Desktop/libensemble/libensemble/libensemble/alloc_funcs/give_sim_work_first.py", line 84, in give_sim_work_first
    gen_work(Work, i, [], [], persis_info[i])
KeyError: 1
```

- [ ] Fix ``alloc_f`` OR initialize ``persis_info`` with workerIDs in ``libE.py``

**Comment by jlnav** [comment]
Closed by #578
